-- Create Error Logging Table
CREATE TABLE migration_errors (
    error_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_message VARCHAR2(2000),
    error_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    procedure_name VARCHAR2(100),
    error_data CLOB
);