-- 1. Suppliers Table
CREATE TABLE suppliers (
    supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR2(255) NOT NULL,
    contact_name VARCHAR2(255),
    contact_number VARCHAR2(20),
    address VARCHAR2(500),
    email VARCHAR2(255),
    CONSTRAINT supplier_email_uk UNIQUE (email)
);

-- 2. Orders Table
CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id NUMBER NOT NULL,
    order_ref VARCHAR2(100) NOT NULL UNIQUE,
    order_date DATE NOT NULL,
    total_amount NUMBER(12, 2),
    description VARCHAR2(2000),
    status VARCHAR2(50),
    CONSTRAINT fk_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
);

-- 3. Order Lines Table (For individual order items)
CREATE TABLE order_lines (
    order_line_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    line_amount NUMBER(12, 2),
    description VARCHAR2(2000),
    CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

-- 4. Invoices Table
CREATE TABLE invoices (
    invoice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    invoice_ref VARCHAR2(100) NOT NULL UNIQUE,
    invoice_date DATE NOT NULL,
    status VARCHAR2(50),
    hold_reason VARCHAR2(500),
    amount NUMBER(12, 2),
    description VARCHAR2(2000),
    CONSTRAINT fk_invoice_order FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

-- Additional indexes to improve performance on common queries
CREATE INDEX idx_order_supplier ON orders(supplier_id);
CREATE INDEX idx_invoice_order ON invoices(order_id);